"""Add role field to users table

Revision ID: 136fbc07d6ce
Revises: 61aec3747f55
Create Date: 2025-07-31 18:52:58.884789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136fbc07d6ce'
down_revision = '61aec3747f55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ### 