"""projects_fnprc

Revision ID: 2565bde4d4eb
Revises: 35d74bf85f53
Create Date: 2025-08-01 13:55:01.680860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2565bde4d4eb'
down_revision = '35d74bf85f53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.create_table('project_fnprc',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('final_price', mysql.DECIMAL(10,2), nullable=True),
    sa.Column('calc_percentage', mysql.DECIMAL(5,2), nullable=True),
    sa.Column('calc_amount', mysql.DECIMAL(10,2), nullable=True), 
    sa.Column('variance_percentage', mysql.DECIMAL(5,2), nullable=True),
    sa.Column('modified_amount', mysql.DECIMAL(10,2), nullable=True),
    sa.Column('modified_percentage', mysql.DECIMAL(5,2), nullable=True),
    sa.Column('final_price_percentage', mysql.DECIMAL(5,2), nullable=True),
    sa.Column('alarm', mysql.TINYINT(1), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_fnprc_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_fnprc_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_table('project_fnprc')
    # ### end Alembic commands ### 