"""projects_qtmat

Revision ID: 35d74bf85f53
Revises: 293a2b53fda6
Create Date: 2025-08-01 13:53:35.827523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35d74bf85f53'
down_revision = '293a2b53fda6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_qtmat',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quoted_materials', mysql.TEXT(), nullable=True),
    sa.Column('alarm', mysql.TEXT(), nullable=True),
    sa.Column('cost', mysql.TEXT(), nullable=True),
    sa.Column('adjustment_percent', mysql.TEXT(), nullable=True),
    sa.Column('adjustment_amount', mysql.TEXT(), nullable=True),
    sa.Column('adjusted_cost', mysql.TEXT(), nullable=True),
    sa.Column('vendor', mysql.TEXT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('code', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_qtmat_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_qtmat_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
   
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.drop_table('project_qtmat')
   
    # ### end Alembic commands ### 