"""Rename project_items table to project_ext

Revision ID: 40d90b5672cb
Revises: 136fbc07d6ce
Create Date: 2025-08-01 11:23:19.565450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40d90b5672cb'
down_revision = '136fbc07d6ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_ext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('trade_price', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.String(length=50), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('link_price', sa.Float(), nullable=True),
    sa.Column('cost_adjustment_percent', sa.Float(), nullable=True),
    sa.Column('net_cost', sa.Float(), nullable=True),
    sa.Column('db_labor', sa.Float(), nullable=True),
    sa.Column('labor', sa.Float(), nullable=True),
    sa.Column('labor_unit', sa.String(length=50), nullable=True),
    sa.Column('labor_adjustment_percent', sa.Float(), nullable=True),
    sa.Column('total_material', sa.Float(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('material_condition', sa.String(length=100), nullable=True),
    sa.Column('labor_condition', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=20), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('manufacturer_name', sa.String(length=200), nullable=True),
    sa.Column('catalog_number', sa.String(length=100), nullable=True),
    sa.Column('price_code', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('supplier_code', sa.String(length=100), nullable=True),
    sa.Column('sort_code_1', sa.String(length=100), nullable=True),
    sa.Column('sort_code_2', sa.String(length=100), nullable=True),
    sa.Column('sort_code_3', sa.String(length=100), nullable=True),
    sa.Column('sort_code_4', sa.String(length=100), nullable=True),
    sa.Column('sort_code_5', sa.String(length=100), nullable=True),
    sa.Column('sort_code_6', sa.String(length=100), nullable=True),
    sa.Column('sort_code_7', sa.String(length=100), nullable=True),
    sa.Column('sort_code_8', sa.String(length=100), nullable=True),
    sa.Column('quick_takeoff_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_ext_id'), 'project_ext', ['id'], unique=False)
  
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('project_ext')
    # ### end Alembic commands ### 