"""Rename project_items table to project_ext

Revision ID: 40d90b5672cb
Revises: 8d6752f845c2
Create Date: 2025-08-01 11:23:19.565450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40d90b5672cb'
down_revision = '8d6752f845c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_ext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('trade_price', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.String(length=50), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('link_price', sa.Float(), nullable=True),
    sa.Column('cost_adjustment_percent', sa.Float(), nullable=True),
    sa.Column('net_cost', sa.Float(), nullable=True),
    sa.Column('db_labor', sa.Float(), nullable=True),
    sa.Column('labor', sa.Float(), nullable=True),
    sa.Column('labor_unit', sa.String(length=50), nullable=True),
    sa.Column('labor_adjustment_percent', sa.Float(), nullable=True),
    sa.Column('total_material', sa.Float(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('material_condition', sa.String(length=100), nullable=True),
    sa.Column('labor_condition', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=20), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('manufacturer_name', sa.String(length=200), nullable=True),
    sa.Column('catalog_number', sa.String(length=100), nullable=True),
    sa.Column('price_code', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('supplier_code', sa.String(length=100), nullable=True),
    sa.Column('sort_code_1', sa.String(length=100), nullable=True),
    sa.Column('sort_code_2', sa.String(length=100), nullable=True),
    sa.Column('sort_code_3', sa.String(length=100), nullable=True),
    sa.Column('sort_code_4', sa.String(length=100), nullable=True),
    sa.Column('sort_code_5', sa.String(length=100), nullable=True),
    sa.Column('sort_code_6', sa.String(length=100), nullable=True),
    sa.Column('sort_code_7', sa.String(length=100), nullable=True),
    sa.Column('sort_code_8', sa.String(length=100), nullable=True),
    sa.Column('quick_takeoff_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_ext_id'), 'project_ext', ['id'], unique=False)
    op.drop_index(op.f('ix_project_items_id'), table_name='project_items')
    op.drop_table('project_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('quantity', mysql.FLOAT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('trade_price', mysql.FLOAT(), nullable=True),
    sa.Column('price_unit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('discount_percent', mysql.FLOAT(), nullable=True),
    sa.Column('link_price', mysql.FLOAT(), nullable=True),
    sa.Column('cost_adjustment_percent', mysql.FLOAT(), nullable=True),
    sa.Column('net_cost', mysql.FLOAT(), nullable=True),
    sa.Column('db_labor', mysql.FLOAT(), nullable=True),
    sa.Column('labor', mysql.FLOAT(), nullable=True),
    sa.Column('labor_unit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('labor_adjustment_percent', mysql.FLOAT(), nullable=True),
    sa.Column('total_material', mysql.FLOAT(), nullable=True),
    sa.Column('total_hours', mysql.FLOAT(), nullable=True),
    sa.Column('material_condition', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('labor_condition', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('weight', mysql.FLOAT(), nullable=True),
    sa.Column('weight_unit', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('total_weight', mysql.FLOAT(), nullable=True),
    sa.Column('manufacturer_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('catalog_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('price_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('reference', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('supplier_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('supplier_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sort_code_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sort_code_2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sort_code_3', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sort_code_4', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sort_code_5', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sort_code_6', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sort_code_7', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sort_code_8', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('quick_takeoff_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_items_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_items_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_items_id'), 'project_items', ['id'], unique=False)
    op.drop_index(op.f('ix_project_ext_id'), table_name='project_ext')
    op.drop_table('project_ext')
    # ### end Alembic commands ### 