"""projects_lbfac

Revision ID: 8355f29da39e
Revises: e346a02c02da
Create Date: 2025-08-01 13:34:01.016348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8355f29da39e'
down_revision = 'e346a02c02da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.create_table('project_lbfac',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('labor_factoring', mysql.TEXT(), nullable=True),
    sa.Column('factor', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('direct_hours_percentage', mysql.DECIMAL(10, 2), nullable=True), 
    sa.Column('hours', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('rate', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('subtotal', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('burden_percentage', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('fringe_amount', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('burden_total', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('fringe_total', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('total', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('full_rate', mysql.DECIMAL(10, 2), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_lbfac_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_lbfac_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_lbfac')
    # ### end Alembic commands ### 