"""projects_inclb

Revision ID: e346a02c02da
Revises: f299ffff52d9
Create Date: 2025-08-01 13:30:38.067235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e346a02c02da'
down_revision = 'f299ffff52d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.create_table('project_inclb',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('incidental_labor', mysql.TEXT(), nullable=True),
    sa.Column('hours', mysql.TEXT(), nullable=True),
    sa.Column('rate', mysql.TEXT(), nullable=True),
    sa.Column('sub_total', mysql.TEXT(), nullable=True),
    sa.Column('brdn', mysql.TEXT(), nullable=True),
    sa.Column('frng', mysql.TEXT(), nullable=True),
    sa.Column('brdn_total', mysql.TEXT(), nullable=True),
    sa.Column('frng_total', mysql.TEXT(), nullable=True),
    sa.Column('total', mysql.TEXT(), nullable=True),
    sa.Column('full_rate', mysql.TEXT(), nullable=True),
    sa.Column('code', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_inclb_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_inclb_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('project_inclb')
    # ### end Alembic commands ### 