"""projects_dirlib

Revision ID: f299ffff52d9
Revises: 40d90b5672cb
Create Date: 2025-08-01 11:27:48.852931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f299ffff52d9'
down_revision = '40d90b5672cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_dirlb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('labor_type', mysql.TEXT(), nullable=True),
    sa.Column('crew', mysql.TEXT(), nullable=True),
    sa.Column('hours', mysql.TEXT(), nullable=True),
    sa.Column('rate', mysql.TEXT(), nullable=True),
    sa.Column('sub_total', mysql.TEXT(), nullable=True),
    sa.Column('brdn', mysql.TEXT(), nullable=True),
    sa.Column('frng', mysql.TEXT(), nullable=True),
    sa.Column('brdn_total', mysql.TEXT(), nullable=True),
    sa.Column('frng_total', mysql.TEXT(), nullable=True),
    sa.Column('total', mysql.TEXT(), nullable=True),
    sa.Column('full_rate', mysql.TEXT(), nullable=True),
    sa.Column('code', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_dirlb_id'), 'project_dirlb', ['id'], unique=False)
  
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_dirlb')
    pass
    # ### end Alembic commands ### 